server:
  port: 9191

# configure routes and fallbacks
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/employees/**
        filters:
          - name: CircuitBreaker
            args:
              name: EMPLOYEE-SERVICE
              fallbackuri: forward:/employeeServiceFallBack

      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/departments/**
        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/departmentServiceFallBack

      - id: ADDRESS-SERVICE
        uri: lb://ADDRESS-SERVICE
        predicates:
          - Path=/addresses/**
        filters:
          - name: CircuitBreaker
            args:
              name: ADDRESS-SERVICE
              fallbackuri: forward:/addressServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

# enable hystrix dashboard
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream